version: "3.9"

services:
  app:
    build:
      context: .
      target: dev   
      # change to "prod" in production
    container_name: social-app
    volumes:
      - .:/app      # only needed for dev (so Air sees changes)
      - /app/tmp
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: social-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: social
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
